apiVersion: v1
entries:
  discovery:
  - apiVersion: v2
    appVersion: 1.4.5
    created: "2023-12-17T19:09:32.770947-05:00"
    dependencies:
    - name: db
      repository: ""
      version: 1.0.0
    - name: redis
      repository: ""
      version: 1.0.0
    - name: celery-worker
      repository: ""
      version: 0.9.1
    description: The RedHat Product Discovery tool is designed to help users collect
      data about their usage of specific Red Hat software.
    digest: 98504fda30a053df0713034e9ddd54040d97d1c01224d605ff1716fc5e0b1854
    icon: https://abellotti.github.io/quipucords-helm-repo/charts/discovery/icon.png
    name: discovery
    type: application
    urls:
    - discovery-0.9.1.tgz
    version: 0.9.1
generated: "2023-12-17T19:09:32.769215-05:00"
